import { test, expect } from '@playwright/test'

test('desktop: WebGL, navigation, projects, language and contact', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('.site-shell')).toHaveAttribute('aria-hidden', 'false')
  await expect(page.locator('h1')).toContainText('GRAVIDADE.')
  await expect(page.locator('.black-hole canvas')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/desktop.png' })
  await page.getByRole('button', { name: 'Explorar singularidade', exact: true }).click()
  await expect(page.locator('.explore-dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Zoom +', exact: true }).click()
  await expect(page.locator('.explore-controls')).toContainText('1.15×')
  await page.keyboard.press('Escape')
  await expect(page.locator('.explore-dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Ver todos os projetos', exact: true }).click()
  await expect(page.locator('.project')).toHaveCount(4)
  await page.getByRole('button', { name: 'Explorar projeto: ORBITAL®', exact: true }).first().click()
  await expect(page.locator('.project-dialog')).toBeVisible()
  await expect(page.locator('.dialog-body')).toContainText('Projeto demonstrativo')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Ver menos projetos', exact: true }).click()
  await page.locator('.faq summary').filter({ hasText: 'Qual é o investimento para um projeto?' }).click()
  await expect(page.getByText('Cada proposta considera', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Branding', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Branding', exact: true })).toHaveAttribute('aria-pressed','true')
  await page.getByPlaceholder('Seu nome / empresa *').fill('Teste Studio')
  await page.getByPlaceholder('Seu e-mail *').fill('teste@example.com')
  await page.getByPlaceholder('O que vamos criar juntos? *').fill('Uma nova identidade visual.')
  await page.getByRole('button', { name: 'Indicação', exact: true }).click()
  await page.getByRole('button', { name: 'Solicitar reunião de diagnóstico', exact: true }).click()
  await expect(page.locator('.form-result')).toBeVisible()
  await expect(page.locator('.form-result textarea')).toHaveValue(/Teste Studio/)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  await expect(page.locator('h1')).toContainText('GRAVITY.')
  await page.reload()
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('h1')).toContainText('GRAVITY.')
  expect(errors).toEqual([])
})

test('mobile: responsive layout and menu', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('.site-shell')).toHaveAttribute('aria-hidden', 'false')
  await page.screenshot({ path: 'test-results/mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Menu', exact: true }).click()
  await expect(page.locator('.navigation')).toBeVisible()
  await page.locator('.navigation').getByRole('link', { name: '04 Contato' }).click()
  await expect(page.locator('.navigation')).not.toBeVisible()
  await expect(page.locator('#contato')).toBeInViewport()
  await page.screenshot({ path: 'test-results/mobile-contact.png' })
})

test('reduced motion and WebGL fallback keep content available', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { return type === 'webgl' ? null : original.call(this, type, ...args) } })
  await page.goto('/')
  await expect(page.locator('.loader')).toHaveCount(0)
  await expect(page.locator('.hole-fallback')).toBeVisible()
  await expect(page.locator('.marquee-track')).toHaveCSS('animation-name', 'none')
  await expect(page.locator('h1')).toContainText('GRAVIDADE.')
})
