import { test, expect } from '@playwright/test'

test('desktop: WebGL, navigation, projects, language and visible sections', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('.site-shell')).toHaveAttribute('aria-hidden', 'false')
  await expect(page.locator('h1')).toContainText('GRAVIDADE.')
  await expect(page.locator('.black-hole canvas')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/desktop.png' })
  await page.getByRole('button', { name: 'Explorar singularidade', exact: true }).click()
  await expect(page.locator('.explore-dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Zoom +', exact: true }).click()
  await expect(page.locator('.explore-controls')).toContainText('1.15×')
  await page.keyboard.press('Escape')
  await expect(page.locator('.explore-dialog')).not.toBeVisible()
  await page.getByRole('button', { name: 'Ver todos os projetos', exact: true }).click()
  await expect(page.locator('.project')).toHaveCount(4)
  await page.getByRole('button', { name: 'Explorar projeto: ORBITAL®', exact: true }).first().click()
  await expect(page.locator('.project-dialog')).toBeVisible()
  await expect(page.locator('.dialog-body')).toContainText('Projeto demonstrativo')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Ver menos projetos', exact: true }).click()
  await expect(page.locator('.project')).toHaveCount(2)
  // These sections remain in the source but are intentionally hidden by the
  // existing design. Animation setup must not restore them or their navigation.
  await expect(page.locator('.faq')).toBeHidden()
  await expect(page.locator('.contact')).toBeHidden()
  await expect(page.locator('.header-contact')).toBeHidden()
  await expect(page.locator('.navigation a[href="#contato"]')).toBeHidden()
  const secondService = page.locator('.service').nth(1)
  await secondService.locator('summary').click()
  await expect(secondService).toHaveAttribute('open', '')
  await expect(secondService.locator('.service-content')).toBeVisible()
  await expect(page.locator('.service').first()).not.toHaveAttribute('open', '')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('lang','en')
  await expect(page.locator('h1')).toContainText('GRAVITY.')
  await page.reload()
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('h1')).toContainText('GRAVITY.')
  expect(errors).toEqual([])
})

test('mobile: responsive layout and menu', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.locator('.intro-stage').waitFor({ state: 'attached' })
  await page.keyboard.press('Escape')
  await expect(page.locator('.site-shell')).toHaveAttribute('aria-hidden', 'false')
  await page.screenshot({ path: 'test-results/mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('#estudio').scrollIntoViewIfNeeded()
  await expect(page.locator('#estudio')).toBeInViewport()
  await page.screenshot({ path: 'test-results/mobile-studio.png' })
})

test('reduced motion and WebGL fallback keep content available', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(type, ...args) { return type === 'webgl' ? null : original.call(this, type, ...args) } })
  await page.goto('/')
  await expect(page.locator('.loader')).toHaveCount(0)
  await expect(page.locator('.hole-fallback')).toBeVisible()
  await expect(page.locator('.marquee-track')).toHaveCSS('animation-name', 'none')
  await expect(page.locator('h1')).toContainText('GRAVIDADE.')
})
